# Generated by Django 5.1.7 on 2025-03-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_tickettype_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='name',
        ),
    ]
