# Generated by Django 5.1.7 on 2025-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_tickettype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='name',
            field=models.CharField(default='Unnamed Ticket Type', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
