# Generated by Django 5.1.7 on 2025-03-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_tickettype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='name',
        ),
    ]
